name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: FabioBentoLuiz/action-test@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
